{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/build"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "docker info"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "docker pull quay.io/wakaba/docker-perl-app-base && docker pull minio/minio && docker pull mariadb && docker pull quay.io/wakaba/chromedriver:chromium && docker pull quay.io/wakaba/firefoxdriver:stable"
               }
            },
            {
               "run" : {
                  "command" : "make deps-circleci"
               }
            },
            {
               "run" : {
                  "command" : "docker info"
               }
            },
            {
               "run" : {
                  "command" : "docker build -t quay.io/wakaba/gruwa ."
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/build"
               }
            },
            {
               "run" : {
                  "command" : "mkdir -p .ciconfigtemp/dockerimages/quay.io/wakaba/"
               }
            },
            {
               "run" : {
                  "command" : "docker save -o .ciconfigtemp/dockerimages/quay.io/wakaba/gruwa.tar quay.io/wakaba/gruwa"
               }
            },
            {
               "persist_to_workspace" : {
                  "paths" : [
                     ".ciconfigtemp"
                  ],
                  "root" : "./"
               }
            }
         ]
      },
      "deploy_master" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/wakaba/gruwa.tar"
               }
            },
            {
               "deploy" : {
                  "command" : "docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS quay.io || docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io"
               }
            },
            {
               "deploy" : {
                  "command" : "docker push quay.io/wakaba/gruwa"
               }
            },
            {
               "deploy" : {
                  "command" : "curl -sSf $BWALLER_URL | BWALL_GROUP=docker BWALL_NAME=quay.io/wakaba/gruwa bash"
               }
            }
         ]
      },
      "deploy_nightly" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/wakaba/gruwa.tar"
               }
            },
            {
               "deploy" : {
                  "command" : "git fetch --unshallow origin master || git fetch origin master\u000Agit checkout master || git checkout -b master origin/master\u000Agit merge -m \u0022auto-merge $CIRCLE_BRANCH ($CIRCLE_SHA1) into master\u0022 $CIRCLE_SHA1\u000Agit push origin master\u000Acurl -sSf $BWALLER_URL | BWALL_GROUP=merger.$CIRCLE_BRANCH BWALL_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME bash"
               }
            }
         ]
      },
      "deploy_staging" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/wakaba/gruwa.tar"
               }
            },
            {
               "deploy" : {
                  "command" : "git fetch --unshallow origin master || git fetch origin master\u000Agit checkout master || git checkout -b master origin/master\u000Agit merge -m \u0022auto-merge $CIRCLE_BRANCH ($CIRCLE_SHA1) into master\u0022 $CIRCLE_SHA1\u000Agit push origin master\u000Acurl -sSf $BWALLER_URL | BWALL_GROUP=merger.$CIRCLE_BRANCH BWALL_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME bash"
               }
            }
         ]
      },
      "gaa4" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "git config --global user.email \u0022temp@circleci.test\u0022;git config --global user.name \u0022CircleCI\u0022"
               }
            },
            {
               "run" : {
                  "command" : "make deps"
               }
            },
            {
               "run" : {
                  "command" : "make updatenightly"
               }
            },
            {
               "deploy" : {
                  "command" : "git diff-index --quiet HEAD --cached || git commit -m auto"
               }
            },
            {
               "deploy" : {
                  "command" : "git push origin \u002B`git rev-parse HEAD`:refs/heads/nightly"
               }
            }
         ]
      },
      "test" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/test"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/wakaba/gruwa.tar"
               }
            },
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "rm -fr $CIRCLE_ARTIFACTS/ss.pid"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "TEST_APP_DOCKER_IMAGE=quay.io/wakaba/gruwa ./perl t_deps/bin/env-for-circleci.pl > $CIRCLE_ARTIFACTS/servers-http-$CIRCLE_NODE_INDEX.txt.dat 2>&1"
               }
            },
            {
               "run" : {
                  "command" : "while [ ! -e $CIRCLE_ARTIFACTS/ss.pid ]; do sleep 1; done"
               }
            },
            {
               "run" : {
                  "command" : "if [ ! -e $CIRCLE_ARTIFACTS/ss.pid ]; then cat $CIRCLE_ARTIFACTS/ss.env; fi; cat $CIRCLE_ARTIFACTS/ss.pid"
               }
            },
            {
               "run" : {
                  "command" : "SS_ENV_FILE=$CIRCLE_ARTIFACTS/ss.env make test-http-circleci"
               }
            },
            {
               "run" : {
                  "command" : "kill `cat $CIRCLE_ARTIFACTS/ss.pid`"
               }
            },
            {
               "run" : {
                  "command" : "while [ -e $CIRCLE_ARTIFACTS/ss.pid ]; do sleep 1; done"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "IS_BROWSER_TEST=1 TEST_WD_BROWSER=chromium TEST_APP_DOCKER_IMAGE=quay.io/wakaba/gruwa ./perl t_deps/bin/env-for-circleci.pl > $CIRCLE_ARTIFACTS/servers-chromium-$CIRCLE_NODE_INDEX.txt.dat 2>&1"
               }
            },
            {
               "run" : {
                  "command" : "while [ ! -e $CIRCLE_ARTIFACTS/ss.pid ]; do sleep 1; done"
               }
            },
            {
               "run" : {
                  "command" : "if [ ! -e $CIRCLE_ARTIFACTS/ss.pid ]; then cat $CIRCLE_ARTIFACTS/ss.env; fi; cat $CIRCLE_ARTIFACTS/ss.pid"
               }
            },
            {
               "run" : {
                  "command" : "SS_ENV_FILE=$CIRCLE_ARTIFACTS/ss.env make test-browser-circleci"
               }
            },
            {
               "run" : {
                  "command" : "kill `cat $CIRCLE_ARTIFACTS/ss.pid`"
               }
            },
            {
               "run" : {
                  "command" : "while [ -e $CIRCLE_ARTIFACTS/ss.pid ]; do sleep 1; done"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "IS_BROWSER_TEST=1 TEST_WD_BROWSER=firefox TEST_APP_DOCKER_IMAGE=quay.io/wakaba/gruwa ./perl t_deps/bin/env-for-circleci.pl > $CIRCLE_ARTIFACTS/servers-firefox-$CIRCLE_NODE_INDEX.txt.dat 2>&1"
               }
            },
            {
               "run" : {
                  "command" : "while [ ! -e $CIRCLE_ARTIFACTS/ss.pid ]; do sleep 1; done"
               }
            },
            {
               "run" : {
                  "command" : "if [ ! -e $CIRCLE_ARTIFACTS/ss.pid ]; then cat $CIRCLE_ARTIFACTS/ss.env; fi; cat $CIRCLE_ARTIFACTS/ss.pid"
               }
            },
            {
               "run" : {
                  "command" : "TEST_WD_BROWSER=firefox SS_ENV_FILE=$CIRCLE_ARTIFACTS/ss.env make test-browser-circleci"
               }
            },
            {
               "run" : {
                  "command" : "true"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/test"
               }
            }
         ]
      }
   },
   "version" : "2.1",
   "workflows" : {
      "build" : {
         "jobs" : [
            {
               "build" : {
               }
            },
            {
               "test" : {
                  "requires" : [
                     "build"
                  ]
               }
            },
            {
               "deploy_master" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "master"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test"
                  ]
               }
            },
            {
               "deploy_nightly" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "nightly"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test"
                  ]
               }
            },
            {
               "deploy_staging" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "staging"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test"
                  ]
               }
            }
         ]
      },
      "gaa4" : {
         "jobs" : [
            "gaa4"
         ],
         "triggers" : [
            {
               "schedule" : {
                  "cron" : "16 21 * * *",
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "master"
                        ]
                     }
                  }
               }
            }
         ]
      },
      "version" : 2
   }
}
